# -*- coding: utf-8 -*-
"""Jade_Webb_Term_Project_Submission.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16lu873_W6XGUKNJQM8DfjB3pE4oSkwcl

# <b>CS156 (Introduction to AI), Fall 2021</b>
# <u><b>Final term project</b></u>

### Roster Name: Jade Webb
### Preferred Name (if different): n/a
### Student ID: 013155207
### Email address: jade.webb@sjsu.edu
Any special notes or anything you would like to communicate to me about this project submission goes in here.

##  <u> Project description/introduction text (the background information) </u>

The problem for my project is to predict whether a patient will have a stroke based on
measured patient data. Based on certain numerical and categorial factors, a patient may be more susceptible to having a
stroke. This is an interesting problem, because there is not sure-fire method that is used to predict a stroke. This is an
important problem to solve, because strokes are debilitating and life-threatening occurrences, so it is crucial to detect
warning signs that an individual may have a stroke in the future. There are many studies regarding stroke-prediction.
These studies are complex with large amounts of data that is more complex. Some studies regard x-rays and other patient images, and many target a specific type of stroke. They also analyze trends for extensive data collected on each patient. These studies are often very successful, with prediction success rates in the high nineties.
These studies often utilize machine learning models including neural networks due to the complex nature of the data. I agree with their approach as they are
exhaustive, specific, and achieves high success rates.

##  <u> Machine learning algorithm selected for this project </u>

Decision Tree Model: supervised non-parametric model that classifies data through a series of splits based on criteria associated with decision nodes that form a hierarchy.

Random Forest Model: ensemble method comprised of many decision trees formed from independent variable subsets. The final prediction is averaged across the classification produced by the inner decision trees.

##  <u> Dataset source </u>

I will be using the Stroke Prediction Dataset. This dataset contains patient data regarding attributes
that may be stroke indicators, and entries are classified based on whether or not the patient has had a stroke. There are
5110 observations in the dataset. 249 of these observations are positive (patient has had a stroke) and 4861 of these
observations are negative (patient has not had a stroke). This dataset can be found at
https://www.kaggle.com/fedesoriano/stroke-prediction-dataset?select=healthcare-dataset-stroke-data.csv

##  <u> References and sources </u>

*    https://towardsdatascience.com/7-ways-to-handle-missing-values-in-machine-learning-1a6326adf79e for handling missing data
*    https://stackoverflow.com/questions/59447378/sklearn-plot-tree-plot-is-too-small for increasing decision tree font size
*    https://scikit-learn.org/stable/auto_examples/model_selection/plot_confusion_matrix.html for confusion matrix

##  <u>Solution</u>

### Load libraries and set random number generator seed
"""

import numpy as np
import pandas as pd
from google.colab import drive
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import plot_confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn import tree

drive.mount('/content/gdrive')

np.random.seed(42)

"""### Code the solution

####Load Stroke Dataset
"""

stroke_df = pd.read_csv('gdrive/My Drive/Colab Notebooks/CS 156/Term Project/healthcare-dataset-stroke-data.csv')
stroke_df

"""####Format some rows with dummies"""

gender = pd.get_dummies(stroke_df.iloc[:, 1:2], columns=stroke_df.iloc[:, 1:2].columns, prefix=stroke_df.iloc[:, 1:2].columns)
married = pd.get_dummies(stroke_df.iloc[:, 5:6], columns=stroke_df.iloc[:, 5:6].columns, prefix=stroke_df.iloc[:, 5:6].columns)
work = pd.get_dummies(stroke_df.iloc[:, 6:7], columns=stroke_df.iloc[:, 6:7].columns, prefix=stroke_df.iloc[:, 6:7].columns)
residence = pd.get_dummies(stroke_df.iloc[:, 7:8], columns=stroke_df.iloc[:, 7:8].columns, prefix=stroke_df.iloc[:, 7:8].columns)
smoke = pd.get_dummies(stroke_df.iloc[:, 10:11], columns=stroke_df.iloc[:, 10:11].columns, prefix=stroke_df.iloc[:, 10:11].columns)

stroke = pd.DataFrame(stroke_df.id)
stroke = stroke.join(gender)
stroke = stroke.join(stroke_df.iloc[:, 2:5])
stroke = stroke.join(married)
stroke = stroke.join(work)
stroke = stroke.join(residence)
stroke = stroke.join(stroke_df.iloc[:, 8:10])
stroke = stroke.join(smoke)
stroke = stroke.join(stroke_df.iloc[:, 11])
stroke

"""####Replace NaN bmi values with mean"""

stroke.isnull().sum()

stroke['bmi'] = stroke['bmi'].replace(np.NaN, stroke['bmi'].mean())

"""####Split Test/Training Data"""

X = stroke.iloc[:, 1:22]
Y = stroke.iloc[:, 22]

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0, stratify=Y)
X_train.shape, Y_train.shape, X_test.shape, Y_test.shape

"""####Train Decision Tree Model"""

model = DecisionTreeClassifier(random_state=0)

model.fit(X_train, Y_train)

print('Accuracy of decision tree model on training set: {:.2f}'.format(model.score(X_train, Y_train)))
print('Accuracy of decision tree model on test set: {:.2f}'.format(model.score(X_test, Y_test)))

accuracies = cross_val_score(model, X_train, Y_train, cv=5)
print('Individual cross-validation accuracies:', accuracies)
print('Mean cross validation accuraccy:', accuracies.mean())

plt.figure(figsize = (300,50))
tree.plot_tree(model, feature_names=stroke.columns, class_names=stroke.columns, filled=True, fontsize=10)
plt.title("Decision Tree Classifier for Stroke Dataset")
plt.show()

titles_options = [("Confusion matrix, without normalization", None),
                  ("Normalized confusion matrix", 'true')]
for title, normalize in titles_options:
    disp = plot_confusion_matrix(model, X_train, Y_train,
                                 display_labels=['no stroke', 'stroke'],
                                 cmap=plt.cm.Blues, values_format='.4g',
                                 normalize=normalize)
    disp.ax_.set_title(title)

    print(title)
    print(disp.confusion_matrix)

plt.show()

titles_options = [("Confusion matrix, without normalization", None),
                  ("Normalized confusion matrix", 'true')]
for title, normalize in titles_options:
    disp = plot_confusion_matrix(model, X_test, Y_test,
                                 display_labels=['no stroke', 'stroke'],
                                 cmap=plt.cm.Blues, values_format='.3g',
                                 normalize=normalize)
    disp.ax_.set_title(title)

    print(title)
    print(disp.confusion_matrix)

plt.show()

"""####Train a Random Forest Classifier"""

model_forest = RandomForestClassifier(random_state=0)

model_forest.fit(X_train, Y_train)

print('Accuracy of random forest model on training set: {:.2f}'.format(model_forest.score(X_train, Y_train)))
print('Accuracy of random forest model on test set: {:.2f}'.format(model_forest.score(X_test, Y_test)))

accuracies = cross_val_score(model_forest, X_train, Y_train, cv=5)
print('Individual cross-validation accuracies:', accuracies)
print('Mean cross validation accuraccy:', accuracies.mean())

titles_options = [("Confusion matrix, without normalization", None),
                  ("Normalized confusion matrix", 'true')]
for title, normalize in titles_options:
    disp = plot_confusion_matrix(model_forest, X_train, Y_train,
                                 display_labels=['no stroke', 'stroke'],
                                 cmap=plt.cm.Blues, values_format='.4g',
                                 normalize=normalize)
    disp.ax_.set_title(title)

    print(title)
    print(disp.confusion_matrix)

plt.show()

titles_options = [("Confusion matrix, without normalization", None),
                  ("Normalized confusion matrix", 'true')]
for title, normalize in titles_options:
    disp = plot_confusion_matrix(model_forest, X_test, Y_test,
                                 display_labels=['no stroke', 'stroke'],
                                 cmap=plt.cm.Blues, values_format='.3g',
                                 normalize=normalize)
    disp.ax_.set_title(title)

    print(title)
    print(disp.confusion_matrix)

plt.show()